[project]
name = "peak-find"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "nbformat>=5.10.4",
    "plotly>=6.1.2",
    "pyqt6>=6.9.1",
    "scipy>=1.15.2",
]
